build_with_mambabuild: true
azure:
  # toggle for storing the conda build_artifacts directory (including the
  # built packages) as an Azure pipeline artifact that can be downloaded
  store_build_artifacts: true
github:
  user_or_org: ericpre
